/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLucideCheck: typeof import('~icons/lucide/check.jsx').default
  const IconLucideCopy: typeof import('~icons/lucide/copy.jsx').default
  const IconOcticonSync16: typeof import('~icons/octicon/sync16.jsx').default
}
