/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char126dashLoginRouteImport } from './routes/~dash.$login'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthDeviceRouteImport } from './routes/auth/device'
import { Route as CreditsAddIdRouteImport } from './routes/credits.add.$id'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126dashLoginRoute = Char126dashLoginRouteImport.update({
  id: '/~dash/$login',
  path: '/~dash/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsAddIdRoute = CreditsAddIdRouteImport.update({
  id: '/credits/add/$id',
  path: '/credits/add/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/error': typeof AuthErrorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/~dash/$login': typeof Char126dashLoginRoute
  '/credits/add/$id': typeof CreditsAddIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/error': typeof AuthErrorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/~dash/$login': typeof Char126dashLoginRoute
  '/credits/add/$id': typeof CreditsAddIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/error': typeof AuthErrorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/~dash/$login': typeof Char126dashLoginRoute
  '/credits/add/$id': typeof CreditsAddIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/playground'
    | '/auth/device'
    | '/auth/error'
    | '/invite/$token'
    | '/~dash/$login'
    | '/credits/add/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/playground'
    | '/auth/device'
    | '/auth/error'
    | '/invite/$token'
    | '/~dash/$login'
    | '/credits/add/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/playground'
    | '/auth/device'
    | '/auth/error'
    | '/invite/$token'
    | '/~dash/$login'
    | '/credits/add/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
  AuthErrorRoute: typeof AuthErrorRoute
  InviteTokenRoute: typeof InviteTokenRoute
  Char126dashLoginRoute: typeof Char126dashLoginRoute
  CreditsAddIdRoute: typeof CreditsAddIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~dash/$login': {
      id: '/~dash/$login'
      path: '/~dash/$login'
      fullPath: '/~dash/$login'
      preLoaderRoute: typeof Char126dashLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits/add/$id': {
      id: '/credits/add/$id'
      path: '/credits/add/$id'
      fullPath: '/credits/add/$id'
      preLoaderRoute: typeof CreditsAddIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  AuthDeviceRoute: AuthDeviceRoute,
  AuthErrorRoute: AuthErrorRoute,
  InviteTokenRoute: InviteTokenRoute,
  Char126dashLoginRoute: Char126dashLoginRoute,
  CreditsAddIdRoute: CreditsAddIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
