name: Main

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: main-${{ github.run_id }}
  cancel-in-progress: true

env:
  WRANGLER_SEND_METRICS: false

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  deploy:
    name: Deploy
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Generate types
        run: pnpm gen:types

      - name: Build
        run: pnpm build

      - name: Deploy to Production
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          wranglerVersion: ""
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
          environment: production
